name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run npm audit
        run: npm install && npm audit
      - name: Run ESLint
        run: |
          npm install
          npx eslint .
